### ISSUE TITLE
Data pada folder submodules tidak terbawa

### ISSUE THREAD

**Issue by fihriaziz** [creasico/laravel-nusa#77]
### Describe the feature

Pada project `laravel-nusa` terdapat folder `submodules`,  didalam pada folder tersebut terdapat folder `cahyadsn-wilayah` dan `w3appdev-kodepos` dimana kedua folder tersebut menyimpan sebuah database. 

Ketika repository ini di `clone` dengan `git clone git@github.com:creasico/laravel-nusa.git`. Data yang terdapat pada folder `submodules` tidak terbawa saat cloning. Apa yang terjadi saat data pada `submodules` tidak ikut terbawa? Terjadi error saat dilakukan `composer import:db`

![Screen Shot 2024-05-31 at 14 13 15](https://github.com/creasico/laravel-nusa/assets/11206650/34bd4b4e-d3f8-4138-b093-a23381af6fdd)

### How to solve

Gunakan perintah `git clone --recurse-submodules git@github.com:creasico/laravel-nusa.git` agar semua data pada `submodules` terbawa saat project ini di clone

**Comment by feryardiant** [comment]
Informasi setup udah ada di contribution guide line di [readme](https://github.com/creasico/laravel-nusa?tab=readme-ov-file#contributing) ya.

So, next time bisa lebih teliti lagi
