### ISSUE TITLE
Query to MySQL not SQLITE

### ISSUE THREAD

**Issue by halowahyudi** [creasico/laravel-nusa#85]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `addresses`.`addressable_type` = App\Models\Tenant\StudentInformation and `addresses`.`addressable_id` = 1 and `addresses`.`addressable_id` is not null) 

any solution/docs?

**Comment by feryardiant** [comment]
Thank you for the report,

Will update the docs soon
